language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install coveralls
# command to run tests
script:
  - python --version
  - python setup.py nosetest
# upload coverage info
after_success:
  - coveralls
