language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv lock -r --dev > requirements.txt
  - pip install -r requirements.txt
# command to run tests
script:
  - python --version
  - nosetests --with-coverage --cover-package=envtools
# upload coverage info
after_success:
  - coveralls
